apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: discounts
#spec:
#  replicas: 1
#  template:
#    spec:
#      containers:
#      - name: 
#        image: shocnt/discounts-service-fixed:latest
