apiVersion: v1
kind: Service
metadata:
  labels:
    tags.datadoghq.com/service: discounts-service
    tags.datadoghq.com/env: development
    tags.datadoghq.com/version: "1.0"
    app: ecommerce
  name: discounts
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    tags.datadoghq.com/service: discounts-service
    tags.datadoghq.com/env: development
    tags.datadoghq.com/version: "1.0"
    app: ecommerce
  type: ClusterIP
